//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveAlert) DeepCopyInto(out *ActiveAlert) {
	*out = *in
	in.Since.DeepCopyInto(&out.Since)
	if in.LastNotified != nil {
		in, out := &in.LastNotified, &out.LastNotified
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveAlert.
func (in *ActiveAlert) DeepCopy() *ActiveAlert {
	if in == nil {
		return nil
	}
	out := new(ActiveAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveJob) DeepCopyInto(out *ActiveJob) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.RunningDuration != nil {
		in, out := &in.RunningDuration, &out.RunningDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveJob.
func (in *ActiveJob) DeepCopy() *ActiveJob {
	if in == nil {
		return nil
	}
	out := new(ActiveJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannel) DeepCopyInto(out *AlertChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannel.
func (in *AlertChannel) DeepCopy() *AlertChannel {
	if in == nil {
		return nil
	}
	out := new(AlertChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelList) DeepCopyInto(out *AlertChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlertChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelList.
func (in *AlertChannelList) DeepCopy() *AlertChannelList {
	if in == nil {
		return nil
	}
	out := new(AlertChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelSpec) DeepCopyInto(out *AlertChannelSpec) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackConfig)
		**out = **in
	}
	if in.PagerDuty != nil {
		in, out := &in.PagerDuty, &out.PagerDuty
		*out = new(PagerDutyConfig)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(EmailConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimiting != nil {
		in, out := &in.RateLimiting, &out.RateLimiting
		*out = new(RateLimitConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelSpec.
func (in *AlertChannelSpec) DeepCopy() *AlertChannelSpec {
	if in == nil {
		return nil
	}
	out := new(AlertChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelStatus) DeepCopyInto(out *AlertChannelStatus) {
	*out = *in
	if in.LastTestTime != nil {
		in, out := &in.LastTestTime, &out.LastTestTime
		*out = (*in).DeepCopy()
	}
	if in.LastAlertTime != nil {
		in, out := &in.LastAlertTime, &out.LastAlertTime
		*out = (*in).DeepCopy()
	}
	if in.LastFailedTime != nil {
		in, out := &in.LastFailedTime, &out.LastFailedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelStatus.
func (in *AlertChannelStatus) DeepCopy() *AlertChannelStatus {
	if in == nil {
		return nil
	}
	out := new(AlertChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertContext) DeepCopyInto(out *AlertContext) {
	*out = *in
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(bool)
		**out = **in
	}
	if in.LogLines != nil {
		in, out := &in.LogLines, &out.LogLines
		*out = new(int32)
		**out = **in
	}
	if in.IncludeInitContainerLogs != nil {
		in, out := &in.IncludeInitContainerLogs, &out.IncludeInitContainerLogs
		*out = new(bool)
		**out = **in
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = new(bool)
		**out = **in
	}
	if in.PodStatus != nil {
		in, out := &in.PodStatus, &out.PodStatus
		*out = new(bool)
		**out = **in
	}
	if in.SuggestedFixes != nil {
		in, out := &in.SuggestedFixes, &out.SuggestedFixes
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertContext.
func (in *AlertContext) DeepCopy() *AlertContext {
	if in == nil {
		return nil
	}
	out := new(AlertContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertingConfig) DeepCopyInto(out *AlertingConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ChannelRefs != nil {
		in, out := &in.ChannelRefs, &out.ChannelRefs
		*out = make([]ChannelRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IncludeContext != nil {
		in, out := &in.IncludeContext, &out.IncludeContext
		*out = new(AlertContext)
		(*in).DeepCopyInto(*out)
	}
	if in.SuppressDuplicatesFor != nil {
		in, out := &in.SuppressDuplicatesFor, &out.SuppressDuplicatesFor
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AlertDelay != nil {
		in, out := &in.AlertDelay, &out.AlertDelay
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SeverityOverrides != nil {
		in, out := &in.SeverityOverrides, &out.SeverityOverrides
		*out = new(SeverityOverrides)
		**out = **in
	}
	if in.SuggestedFixPatterns != nil {
		in, out := &in.SuggestedFixPatterns, &out.SuggestedFixPatterns
		*out = make([]SuggestedFixPattern, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertingConfig.
func (in *AlertingConfig) DeepCopy() *AlertingConfig {
	if in == nil {
		return nil
	}
	out := new(AlertingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScheduleConfig) DeepCopyInto(out *AutoScheduleConfig) {
	*out = *in
	if in.Buffer != nil {
		in, out := &in.Buffer, &out.Buffer
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MissedScheduleThreshold != nil {
		in, out := &in.MissedScheduleThreshold, &out.MissedScheduleThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScheduleConfig.
func (in *AutoScheduleConfig) DeepCopy() *AutoScheduleConfig {
	if in == nil {
		return nil
	}
	out := new(AutoScheduleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelRef) DeepCopyInto(out *ChannelRef) {
	*out = *in
	if in.Severities != nil {
		in, out := &in.Severities, &out.Severities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelRef.
func (in *ChannelRef) DeepCopy() *ChannelRef {
	if in == nil {
		return nil
	}
	out := new(ChannelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobMetrics) DeepCopyInto(out *CronJobMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobMetrics.
func (in *CronJobMetrics) DeepCopy() *CronJobMetrics {
	if in == nil {
		return nil
	}
	out := new(CronJobMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobMonitor) DeepCopyInto(out *CronJobMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobMonitor.
func (in *CronJobMonitor) DeepCopy() *CronJobMonitor {
	if in == nil {
		return nil
	}
	out := new(CronJobMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronJobMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobMonitorList) DeepCopyInto(out *CronJobMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CronJobMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobMonitorList.
func (in *CronJobMonitorList) DeepCopy() *CronJobMonitorList {
	if in == nil {
		return nil
	}
	out := new(CronJobMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronJobMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobMonitorSpec) DeepCopyInto(out *CronJobMonitorSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(CronJobSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DeadManSwitch != nil {
		in, out := &in.DeadManSwitch, &out.DeadManSwitch
		*out = new(DeadManSwitchConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SLA != nil {
		in, out := &in.SLA, &out.SLA
		*out = new(SLAConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SuspendedHandling != nil {
		in, out := &in.SuspendedHandling, &out.SuspendedHandling
		*out = new(SuspendedHandlingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MaintenanceWindows != nil {
		in, out := &in.MaintenanceWindows, &out.MaintenanceWindows
		*out = make([]MaintenanceWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Alerting != nil {
		in, out := &in.Alerting, &out.Alerting
		*out = new(AlertingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DataRetention != nil {
		in, out := &in.DataRetention, &out.DataRetention
		*out = new(DataRetentionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobMonitorSpec.
func (in *CronJobMonitorSpec) DeepCopy() *CronJobMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(CronJobMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobMonitorStatus) DeepCopyInto(out *CronJobMonitorStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(MonitorSummary)
		**out = **in
	}
	if in.CronJobs != nil {
		in, out := &in.CronJobs, &out.CronJobs
		*out = make([]CronJobStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobMonitorStatus.
func (in *CronJobMonitorStatus) DeepCopy() *CronJobMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(CronJobMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobSelector) DeepCopyInto(out *CronJobSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]v1.LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobSelector.
func (in *CronJobSelector) DeepCopy() *CronJobSelector {
	if in == nil {
		return nil
	}
	out := new(CronJobSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobStatus) DeepCopyInto(out *CronJobStatus) {
	*out = *in
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
	if in.LastFailedTime != nil {
		in, out := &in.LastFailedTime, &out.LastFailedTime
		*out = (*in).DeepCopy()
	}
	if in.LastRunDuration != nil {
		in, out := &in.LastRunDuration, &out.LastRunDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.NextScheduledTime != nil {
		in, out := &in.NextScheduledTime, &out.NextScheduledTime
		*out = (*in).DeepCopy()
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(CronJobMetrics)
		**out = **in
	}
	if in.ActiveJobs != nil {
		in, out := &in.ActiveJobs, &out.ActiveJobs
		*out = make([]ActiveJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveAlerts != nil {
		in, out := &in.ActiveAlerts, &out.ActiveAlerts
		*out = make([]ActiveAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobStatus.
func (in *CronJobStatus) DeepCopy() *CronJobStatus {
	if in == nil {
		return nil
	}
	out := new(CronJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataRetentionConfig) DeepCopyInto(out *DataRetentionConfig) {
	*out = *in
	if in.RetentionDays != nil {
		in, out := &in.RetentionDays, &out.RetentionDays
		*out = new(int32)
		**out = **in
	}
	if in.PurgeAfterDays != nil {
		in, out := &in.PurgeAfterDays, &out.PurgeAfterDays
		*out = new(int32)
		**out = **in
	}
	if in.StoreLogs != nil {
		in, out := &in.StoreLogs, &out.StoreLogs
		*out = new(bool)
		**out = **in
	}
	if in.LogRetentionDays != nil {
		in, out := &in.LogRetentionDays, &out.LogRetentionDays
		*out = new(int32)
		**out = **in
	}
	if in.MaxLogSizeKB != nil {
		in, out := &in.MaxLogSizeKB, &out.MaxLogSizeKB
		*out = new(int32)
		**out = **in
	}
	if in.StoreEvents != nil {
		in, out := &in.StoreEvents, &out.StoreEvents
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataRetentionConfig.
func (in *DataRetentionConfig) DeepCopy() *DataRetentionConfig {
	if in == nil {
		return nil
	}
	out := new(DataRetentionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeadManSwitchConfig) DeepCopyInto(out *DeadManSwitchConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MaxTimeSinceLastSuccess != nil {
		in, out := &in.MaxTimeSinceLastSuccess, &out.MaxTimeSinceLastSuccess
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AutoFromSchedule != nil {
		in, out := &in.AutoFromSchedule, &out.AutoFromSchedule
		*out = new(AutoScheduleConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeadManSwitchConfig.
func (in *DeadManSwitchConfig) DeepCopy() *DeadManSwitchConfig {
	if in == nil {
		return nil
	}
	out := new(DeadManSwitchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailConfig) DeepCopyInto(out *EmailConfig) {
	*out = *in
	out.SMTPSecretRef = in.SMTPSecretRef
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailConfig.
func (in *EmailConfig) DeepCopy() *EmailConfig {
	if in == nil {
		return nil
	}
	out := new(EmailConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExitCodeRange) DeepCopyInto(out *ExitCodeRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExitCodeRange.
func (in *ExitCodeRange) DeepCopy() *ExitCodeRange {
	if in == nil {
		return nil
	}
	out := new(ExitCodeRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
	out.Duration = in.Duration
	if in.SuppressAlerts != nil {
		in, out := &in.SuppressAlerts, &out.SuppressAlerts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorSummary) DeepCopyInto(out *MonitorSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorSummary.
func (in *MonitorSummary) DeepCopy() *MonitorSummary {
	if in == nil {
		return nil
	}
	out := new(MonitorSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedSecretKeyRef) DeepCopyInto(out *NamespacedSecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedSecretKeyRef.
func (in *NamespacedSecretKeyRef) DeepCopy() *NamespacedSecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedSecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedSecretRef) DeepCopyInto(out *NamespacedSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedSecretRef.
func (in *NamespacedSecretRef) DeepCopy() *NamespacedSecretRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerDutyConfig) DeepCopyInto(out *PagerDutyConfig) {
	*out = *in
	out.RoutingKeySecretRef = in.RoutingKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerDutyConfig.
func (in *PagerDutyConfig) DeepCopy() *PagerDutyConfig {
	if in == nil {
		return nil
	}
	out := new(PagerDutyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatternMatch) DeepCopyInto(out *PatternMatch) {
	*out = *in
	if in.ExitCode != nil {
		in, out := &in.ExitCode, &out.ExitCode
		*out = new(int32)
		**out = **in
	}
	if in.ExitCodeRange != nil {
		in, out := &in.ExitCodeRange, &out.ExitCodeRange
		*out = new(ExitCodeRange)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternMatch.
func (in *PatternMatch) DeepCopy() *PatternMatch {
	if in == nil {
		return nil
	}
	out := new(PatternMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfig) DeepCopyInto(out *RateLimitConfig) {
	*out = *in
	if in.MaxAlertsPerHour != nil {
		in, out := &in.MaxAlertsPerHour, &out.MaxAlertsPerHour
		*out = new(int32)
		**out = **in
	}
	if in.BurstLimit != nil {
		in, out := &in.BurstLimit, &out.BurstLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfig.
func (in *RateLimitConfig) DeepCopy() *RateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAConfig) DeepCopyInto(out *SLAConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MinSuccessRate != nil {
		in, out := &in.MinSuccessRate, &out.MinSuccessRate
		*out = new(float64)
		**out = **in
	}
	if in.WindowDays != nil {
		in, out := &in.WindowDays, &out.WindowDays
		*out = new(int32)
		**out = **in
	}
	if in.MaxDuration != nil {
		in, out := &in.MaxDuration, &out.MaxDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DurationRegressionThreshold != nil {
		in, out := &in.DurationRegressionThreshold, &out.DurationRegressionThreshold
		*out = new(int32)
		**out = **in
	}
	if in.DurationBaselineWindowDays != nil {
		in, out := &in.DurationBaselineWindowDays, &out.DurationBaselineWindowDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAConfig.
func (in *SLAConfig) DeepCopy() *SLAConfig {
	if in == nil {
		return nil
	}
	out := new(SLAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeverityOverrides) DeepCopyInto(out *SeverityOverrides) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeverityOverrides.
func (in *SeverityOverrides) DeepCopy() *SeverityOverrides {
	if in == nil {
		return nil
	}
	out := new(SeverityOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackConfig) DeepCopyInto(out *SlackConfig) {
	*out = *in
	out.WebhookSecretRef = in.WebhookSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackConfig.
func (in *SlackConfig) DeepCopy() *SlackConfig {
	if in == nil {
		return nil
	}
	out := new(SlackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedFixPattern) DeepCopyInto(out *SuggestedFixPattern) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedFixPattern.
func (in *SuggestedFixPattern) DeepCopy() *SuggestedFixPattern {
	if in == nil {
		return nil
	}
	out := new(SuggestedFixPattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuspendedHandlingConfig) DeepCopyInto(out *SuspendedHandlingConfig) {
	*out = *in
	if in.PauseMonitoring != nil {
		in, out := &in.PauseMonitoring, &out.PauseMonitoring
		*out = new(bool)
		**out = **in
	}
	if in.AlertIfSuspendedFor != nil {
		in, out := &in.AlertIfSuspendedFor, &out.AlertIfSuspendedFor
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuspendedHandlingConfig.
func (in *SuspendedHandlingConfig) DeepCopy() *SuspendedHandlingConfig {
	if in == nil {
		return nil
	}
	out := new(SuspendedHandlingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
	out.URLSecretRef = in.URLSecretRef
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}
