//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveAlert) DeepCopyInto(out *ActiveAlert) {
	*out = *in
	in.Since.DeepCopyInto(&out.Since)
	if in.LastNotified != nil {
		in, out := &in.LastNotified, &out.LastNotified
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveAlert.
func (in *ActiveAlert) DeepCopy() *ActiveAlert {
	if in == nil {
		return nil
	}
	out := new(ActiveAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannel) DeepCopyInto(out *AlertChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannel.
func (in *AlertChannel) DeepCopy() *AlertChannel {
	if in == nil {
		return nil
	}
	out := new(AlertChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelList) DeepCopyInto(out *AlertChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlertChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelList.
func (in *AlertChannelList) DeepCopy() *AlertChannelList {
	if in == nil {
		return nil
	}
	out := new(AlertChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelSpec) DeepCopyInto(out *AlertChannelSpec) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackConfig)
		**out = **in
	}
	if in.PagerDuty != nil {
		in, out := &in.PagerDuty, &out.PagerDuty
		*out = new(PagerDutyConfig)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(EmailConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimiting != nil {
		in, out := &in.RateLimiting, &out.RateLimiting
		*out = new(RateLimitConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelSpec.
func (in *AlertChannelSpec) DeepCopy() *AlertChannelSpec {
	if in == nil {
		return nil
	}
	out := new(AlertChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelStatus) DeepCopyInto(out *AlertChannelStatus) {
	*out = *in
	if in.LastTestTime != nil {
		in, out := &in.LastTestTime, &out.LastTestTime
		*out = (*in).DeepCopy()
	}
	if in.LastAlertTime != nil {
		in, out := &in.LastAlertTime, &out.LastAlertTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelStatus.
func (in *AlertChannelStatus) DeepCopy() *AlertChannelStatus {
	if in == nil {
		return nil
	}
	out := new(AlertChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertContext) DeepCopyInto(out *AlertContext) {
	*out = *in
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(bool)
		**out = **in
	}
	if in.LogLines != nil {
		in, out := &in.LogLines, &out.LogLines
		*out = new(int32)
		**out = **in
	}
	if in.IncludeInitContainerLogs != nil {
		in, out := &in.IncludeInitContainerLogs, &out.IncludeInitContainerLogs
		*out = new(bool)
		**out = **in
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = new(bool)
		**out = **in
	}
	if in.PodStatus != nil {
		in, out := &in.PodStatus, &out.PodStatus
		*out = new(bool)
		**out = **in
	}
	if in.SuggestedFixes != nil {
		in, out := &in.SuggestedFixes, &out.SuggestedFixes
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertContext.
func (in *AlertContext) DeepCopy() *AlertContext {
	if in == nil {
		return nil
	}
	out := new(AlertContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertingConfig) DeepCopyInto(out *AlertingConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ChannelRefs != nil {
		in, out := &in.ChannelRefs, &out.ChannelRefs
		*out = make([]ChannelRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IncludeContext != nil {
		in, out := &in.IncludeContext, &out.IncludeContext
		*out = new(AlertContext)
		(*in).DeepCopyInto(*out)
	}
	if in.SuppressDuplicatesFor != nil {
		in, out := &in.SuppressDuplicatesFor, &out.SuppressDuplicatesFor
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SeverityOverrides != nil {
		in, out := &in.SeverityOverrides, &out.SeverityOverrides
		*out = new(SeverityOverrides)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertingConfig.
func (in *AlertingConfig) DeepCopy() *AlertingConfig {
	if in == nil {
		return nil
	}
	out := new(AlertingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRetryConfig) DeepCopyInto(out *AutoRetryConfig) {
	*out = *in
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
	if in.DelayBetweenRetries != nil {
		in, out := &in.DelayBetweenRetries, &out.DelayBetweenRetries
		*out = new(v1.Duration)
		**out = **in
	}
	if in.OnlyForExitCodes != nil {
		in, out := &in.OnlyForExitCodes, &out.OnlyForExitCodes
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRetryConfig.
func (in *AutoRetryConfig) DeepCopy() *AutoRetryConfig {
	if in == nil {
		return nil
	}
	out := new(AutoRetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScheduleConfig) DeepCopyInto(out *AutoScheduleConfig) {
	*out = *in
	if in.Buffer != nil {
		in, out := &in.Buffer, &out.Buffer
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MissedScheduleThreshold != nil {
		in, out := &in.MissedScheduleThreshold, &out.MissedScheduleThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScheduleConfig.
func (in *AutoScheduleConfig) DeepCopy() *AutoScheduleConfig {
	if in == nil {
		return nil
	}
	out := new(AutoScheduleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelRef) DeepCopyInto(out *ChannelRef) {
	*out = *in
	if in.Severities != nil {
		in, out := &in.Severities, &out.Severities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelRef.
func (in *ChannelRef) DeepCopy() *ChannelRef {
	if in == nil {
		return nil
	}
	out := new(ChannelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobMetrics) DeepCopyInto(out *CronJobMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobMetrics.
func (in *CronJobMetrics) DeepCopy() *CronJobMetrics {
	if in == nil {
		return nil
	}
	out := new(CronJobMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobMonitor) DeepCopyInto(out *CronJobMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobMonitor.
func (in *CronJobMonitor) DeepCopy() *CronJobMonitor {
	if in == nil {
		return nil
	}
	out := new(CronJobMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronJobMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobMonitorList) DeepCopyInto(out *CronJobMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CronJobMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobMonitorList.
func (in *CronJobMonitorList) DeepCopy() *CronJobMonitorList {
	if in == nil {
		return nil
	}
	out := new(CronJobMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronJobMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobMonitorSpec) DeepCopyInto(out *CronJobMonitorSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(CronJobSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DeadManSwitch != nil {
		in, out := &in.DeadManSwitch, &out.DeadManSwitch
		*out = new(DeadManSwitchConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SLA != nil {
		in, out := &in.SLA, &out.SLA
		*out = new(SLAConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]DependencyConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SuspendedHandling != nil {
		in, out := &in.SuspendedHandling, &out.SuspendedHandling
		*out = new(SuspendedHandlingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MaintenanceWindows != nil {
		in, out := &in.MaintenanceWindows, &out.MaintenanceWindows
		*out = make([]MaintenanceWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Remediation != nil {
		in, out := &in.Remediation, &out.Remediation
		*out = new(RemediationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Alerting != nil {
		in, out := &in.Alerting, &out.Alerting
		*out = new(AlertingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobMonitorSpec.
func (in *CronJobMonitorSpec) DeepCopy() *CronJobMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(CronJobMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobMonitorStatus) DeepCopyInto(out *CronJobMonitorStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(MonitorSummary)
		**out = **in
	}
	if in.CronJobs != nil {
		in, out := &in.CronJobs, &out.CronJobs
		*out = make([]CronJobStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobMonitorStatus.
func (in *CronJobMonitorStatus) DeepCopy() *CronJobMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(CronJobMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobSelector) DeepCopyInto(out *CronJobSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]v1.LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobSelector.
func (in *CronJobSelector) DeepCopy() *CronJobSelector {
	if in == nil {
		return nil
	}
	out := new(CronJobSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobStatus) DeepCopyInto(out *CronJobStatus) {
	*out = *in
	if in.LastScheduledTime != nil {
		in, out := &in.LastScheduledTime, &out.LastScheduledTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
	if in.LastFailedTime != nil {
		in, out := &in.LastFailedTime, &out.LastFailedTime
		*out = (*in).DeepCopy()
	}
	if in.LastRunDuration != nil {
		in, out := &in.LastRunDuration, &out.LastRunDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.NextScheduledTime != nil {
		in, out := &in.NextScheduledTime, &out.NextScheduledTime
		*out = (*in).DeepCopy()
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(CronJobMetrics)
		**out = **in
	}
	if in.ActiveAlerts != nil {
		in, out := &in.ActiveAlerts, &out.ActiveAlerts
		*out = make([]ActiveAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRemediation != nil {
		in, out := &in.LastRemediation, &out.LastRemediation
		*out = new(RemediationStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobStatus.
func (in *CronJobStatus) DeepCopy() *CronJobStatus {
	if in == nil {
		return nil
	}
	out := new(CronJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeadManSwitchConfig) DeepCopyInto(out *DeadManSwitchConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MaxTimeSinceLastSuccess != nil {
		in, out := &in.MaxTimeSinceLastSuccess, &out.MaxTimeSinceLastSuccess
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AutoFromSchedule != nil {
		in, out := &in.AutoFromSchedule, &out.AutoFromSchedule
		*out = new(AutoScheduleConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeadManSwitchConfig.
func (in *DeadManSwitchConfig) DeepCopy() *DeadManSwitchConfig {
	if in == nil {
		return nil
	}
	out := new(DeadManSwitchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyConfig) DeepCopyInto(out *DependencyConfig) {
	*out = *in
	if in.AlertOnFailure != nil {
		in, out := &in.AlertOnFailure, &out.AlertOnFailure
		*out = new(bool)
		**out = **in
	}
	if in.SuppressDownstreamAlerts != nil {
		in, out := &in.SuppressDownstreamAlerts, &out.SuppressDownstreamAlerts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyConfig.
func (in *DependencyConfig) DeepCopy() *DependencyConfig {
	if in == nil {
		return nil
	}
	out := new(DependencyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailConfig) DeepCopyInto(out *EmailConfig) {
	*out = *in
	out.SMTPSecretRef = in.SMTPSecretRef
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailConfig.
func (in *EmailConfig) DeepCopy() *EmailConfig {
	if in == nil {
		return nil
	}
	out := new(EmailConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitsConfig) DeepCopyInto(out *GlobalRateLimitsConfig) {
	*out = *in
	if in.MaxAlertsPerMinute != nil {
		in, out := &in.MaxAlertsPerMinute, &out.MaxAlertsPerMinute
		*out = new(int32)
		**out = **in
	}
	if in.MaxRemediationsPerHour != nil {
		in, out := &in.MaxRemediationsPerHour, &out.MaxRemediationsPerHour
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitsConfig.
func (in *GlobalRateLimitsConfig) DeepCopy() *GlobalRateLimitsConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianConfig) DeepCopyInto(out *GuardianConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianConfig.
func (in *GuardianConfig) DeepCopy() *GuardianConfig {
	if in == nil {
		return nil
	}
	out := new(GuardianConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuardianConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianConfigList) DeepCopyInto(out *GuardianConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GuardianConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianConfigList.
func (in *GuardianConfigList) DeepCopy() *GuardianConfigList {
	if in == nil {
		return nil
	}
	out := new(GuardianConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuardianConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianConfigSpec) DeepCopyInto(out *GuardianConfigSpec) {
	*out = *in
	if in.DeadManSwitchInterval != nil {
		in, out := &in.DeadManSwitchInterval, &out.DeadManSwitchInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SLARecalculationInterval != nil {
		in, out := &in.SLARecalculationInterval, &out.SLARecalculationInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HistoryRetention != nil {
		in, out := &in.HistoryRetention, &out.HistoryRetention
		*out = new(HistoryRetentionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MetricsExport != nil {
		in, out := &in.MetricsExport, &out.MetricsExport
		*out = new(MetricsExportConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GlobalRateLimits != nil {
		in, out := &in.GlobalRateLimits, &out.GlobalRateLimits
		*out = new(GlobalRateLimitsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.IgnoredNamespaces != nil {
		in, out := &in.IgnoredNamespaces, &out.IgnoredNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LeaderElection != nil {
		in, out := &in.LeaderElection, &out.LeaderElection
		*out = new(LeaderElectionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(UIConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianConfigSpec.
func (in *GuardianConfigSpec) DeepCopy() *GuardianConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GuardianConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianConfigStatus) DeepCopyInto(out *GuardianConfigStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianConfigStatus.
func (in *GuardianConfigStatus) DeepCopy() *GuardianConfigStatus {
	if in == nil {
		return nil
	}
	out := new(GuardianConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HistoryRetentionConfig) DeepCopyInto(out *HistoryRetentionConfig) {
	*out = *in
	if in.DefaultDays != nil {
		in, out := &in.DefaultDays, &out.DefaultDays
		*out = new(int32)
		**out = **in
	}
	if in.MaxDays != nil {
		in, out := &in.MaxDays, &out.MaxDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HistoryRetentionConfig.
func (in *HistoryRetentionConfig) DeepCopy() *HistoryRetentionConfig {
	if in == nil {
		return nil
	}
	out := new(HistoryRetentionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KillStuckJobsConfig) DeepCopyInto(out *KillStuckJobsConfig) {
	*out = *in
	out.AfterDuration = in.AfterDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KillStuckJobsConfig.
func (in *KillStuckJobsConfig) DeepCopy() *KillStuckJobsConfig {
	if in == nil {
		return nil
	}
	out := new(KillStuckJobsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderElectionConfig) DeepCopyInto(out *LeaderElectionConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.LeaseDuration != nil {
		in, out := &in.LeaseDuration, &out.LeaseDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RenewDeadline != nil {
		in, out := &in.RenewDeadline, &out.RenewDeadline
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RetryPeriod != nil {
		in, out := &in.RetryPeriod, &out.RetryPeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderElectionConfig.
func (in *LeaderElectionConfig) DeepCopy() *LeaderElectionConfig {
	if in == nil {
		return nil
	}
	out := new(LeaderElectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
	out.Duration = in.Duration
	if in.SuppressAlerts != nil {
		in, out := &in.SuppressAlerts, &out.SuppressAlerts
		*out = new(bool)
		**out = **in
	}
	if in.SuppressRemediation != nil {
		in, out := &in.SuppressRemediation, &out.SuppressRemediation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsExportConfig) DeepCopyInto(out *MetricsExportConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsExportConfig.
func (in *MetricsExportConfig) DeepCopy() *MetricsExportConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsExportConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorSummary) DeepCopyInto(out *MonitorSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorSummary.
func (in *MonitorSummary) DeepCopy() *MonitorSummary {
	if in == nil {
		return nil
	}
	out := new(MonitorSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLConfig) DeepCopyInto(out *MySQLConfig) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLConfig.
func (in *MySQLConfig) DeepCopy() *MySQLConfig {
	if in == nil {
		return nil
	}
	out := new(MySQLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedSecretKeyRef) DeepCopyInto(out *NamespacedSecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedSecretKeyRef.
func (in *NamespacedSecretKeyRef) DeepCopy() *NamespacedSecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedSecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedSecretRef) DeepCopyInto(out *NamespacedSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedSecretRef.
func (in *NamespacedSecretRef) DeepCopy() *NamespacedSecretRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerDutyConfig) DeepCopyInto(out *PagerDutyConfig) {
	*out = *in
	out.RoutingKeySecretRef = in.RoutingKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerDutyConfig.
func (in *PagerDutyConfig) DeepCopy() *PagerDutyConfig {
	if in == nil {
		return nil
	}
	out := new(PagerDutyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLConfig) DeepCopyInto(out *PostgreSQLConfig) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLConfig.
func (in *PostgreSQLConfig) DeepCopy() *PostgreSQLConfig {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfig) DeepCopyInto(out *RateLimitConfig) {
	*out = *in
	if in.MaxAlertsPerHour != nil {
		in, out := &in.MaxAlertsPerHour, &out.MaxAlertsPerHour
		*out = new(int32)
		**out = **in
	}
	if in.BurstLimit != nil {
		in, out := &in.BurstLimit, &out.BurstLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfig.
func (in *RateLimitConfig) DeepCopy() *RateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationConfig) DeepCopyInto(out *RemediationConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.KillStuckJobs != nil {
		in, out := &in.KillStuckJobs, &out.KillStuckJobs
		*out = new(KillStuckJobsConfig)
		**out = **in
	}
	if in.AutoRetry != nil {
		in, out := &in.AutoRetry, &out.AutoRetry
		*out = new(AutoRetryConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationConfig.
func (in *RemediationConfig) DeepCopy() *RemediationConfig {
	if in == nil {
		return nil
	}
	out := new(RemediationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationStatus) DeepCopyInto(out *RemediationStatus) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationStatus.
func (in *RemediationStatus) DeepCopy() *RemediationStatus {
	if in == nil {
		return nil
	}
	out := new(RemediationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAConfig) DeepCopyInto(out *SLAConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MinSuccessRate != nil {
		in, out := &in.MinSuccessRate, &out.MinSuccessRate
		*out = new(float64)
		**out = **in
	}
	if in.WindowDays != nil {
		in, out := &in.WindowDays, &out.WindowDays
		*out = new(int32)
		**out = **in
	}
	if in.MaxDuration != nil {
		in, out := &in.MaxDuration, &out.MaxDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DurationPercentiles != nil {
		in, out := &in.DurationPercentiles, &out.DurationPercentiles
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.DurationRegressionThreshold != nil {
		in, out := &in.DurationRegressionThreshold, &out.DurationRegressionThreshold
		*out = new(int32)
		**out = **in
	}
	if in.DurationBaselineWindowDays != nil {
		in, out := &in.DurationBaselineWindowDays, &out.DurationBaselineWindowDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAConfig.
func (in *SLAConfig) DeepCopy() *SLAConfig {
	if in == nil {
		return nil
	}
	out := new(SLAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLiteConfig) DeepCopyInto(out *SQLiteConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLiteConfig.
func (in *SQLiteConfig) DeepCopy() *SQLiteConfig {
	if in == nil {
		return nil
	}
	out := new(SQLiteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeverityOverrides) DeepCopyInto(out *SeverityOverrides) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeverityOverrides.
func (in *SeverityOverrides) DeepCopy() *SeverityOverrides {
	if in == nil {
		return nil
	}
	out := new(SeverityOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackConfig) DeepCopyInto(out *SlackConfig) {
	*out = *in
	out.WebhookSecretRef = in.WebhookSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackConfig.
func (in *SlackConfig) DeepCopy() *SlackConfig {
	if in == nil {
		return nil
	}
	out := new(SlackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.SQLite != nil {
		in, out := &in.SQLite, &out.SQLite
		*out = new(SQLiteConfig)
		**out = **in
	}
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuspendedHandlingConfig) DeepCopyInto(out *SuspendedHandlingConfig) {
	*out = *in
	if in.PauseMonitoring != nil {
		in, out := &in.PauseMonitoring, &out.PauseMonitoring
		*out = new(bool)
		**out = **in
	}
	if in.AlertIfSuspendedFor != nil {
		in, out := &in.AlertIfSuspendedFor, &out.AlertIfSuspendedFor
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuspendedHandlingConfig.
func (in *SuspendedHandlingConfig) DeepCopy() *SuspendedHandlingConfig {
	if in == nil {
		return nil
	}
	out := new(SuspendedHandlingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIConfig) DeepCopyInto(out *UIConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIConfig.
func (in *UIConfig) DeepCopy() *UIConfig {
	if in == nil {
		return nil
	}
	out := new(UIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
	out.URLSecretRef = in.URLSecretRef
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}
