# Full-featured CronJobMonitor
# Demonstrates all available configuration options
apiVersion: guardian.illenium.net/v1alpha1
kind: CronJobMonitor
metadata:
  name: full-featured
  namespace: production
spec:
  # Select CronJobs by label expressions
  selector:
    matchExpressions:
      - key: tier
        operator: In
        values: [critical, high]

  # Dead-man's switch: alert if no successful run within window
  deadManSwitch:
    enabled: true
    maxTimeSinceLastSuccess: 25h

  # SLA tracking: monitor success rates
  sla:
    enabled: true
    minSuccessRate: 95
    windowDays: 7

  # Maintenance windows: suppress alerts during planned maintenance
  maintenanceWindows:
    - name: weekly-maintenance
      schedule: "0 2 * * 0"    # Every Sunday at 2 AM
      duration: 4h
      suppressAlerts: true

  # Alerting configuration
  alerting:
    enabled: true
    channelRefs:
      - name: pagerduty-oncall
        severities: [critical]
      - name: slack-ops
        severities: [critical, warning]
      - name: slack-info
        severities: [info]

    # Override default severities for specific alert types
    severityOverrides:
      jobFailed: critical
      slaBreached: warning
      missedSchedule: warning

    # Suppress duplicate alerts
    suppressDuplicatesFor: 1h

    # Include context in alerts
    context:
      includeLogs: true
      logLines: 100
      includeEvents: true
      includeSuggestedFix: true
