# Monitor CronJobs across multiple namespaces
# Watches specific namespaces with optional label filtering
apiVersion: guardian.illenium.net/v1alpha1
kind: CronJobMonitor
metadata:
  name: multi-namespace-monitor
  namespace: cronjob-guardian
spec:
  selector:
    # Watch specific namespaces
    namespaces:
      - production
      - staging
      - data-pipeline
    # Optionally filter by labels within those namespaces
    matchLabels:
      tier: critical
  deadManSwitch:
    enabled: true
    maxTimeSinceLastSuccess: 25h
  alerting:
    channelRefs:
      - name: slack-ops
