# Test Alert Channels
# Note: These are examples - replace webhook URLs with real endpoints for testing
---
# Webhook channel for critical alerts
apiVersion: guardian.illenium.net/v1alpha1
kind: AlertChannel
metadata:
  name: slack-critical
spec:
  type: webhook
  webhook:
    url: "http://localhost:9999/critical"
    method: POST
    headers:
      Content-Type: application/json
    bodyTemplate: |
      {
        "severity": "{{ .Severity }}",
        "title": "{{ .Title }}",
        "message": "{{ .Message }}",
        "cronjob": "{{ .CronJob.Namespace }}/{{ .CronJob.Name }}",
        "timestamp": "{{ .Timestamp | formatTime "RFC3339" }}"
      }
---
# Webhook channel for warnings
apiVersion: guardian.illenium.net/v1alpha1
kind: AlertChannel
metadata:
  name: slack-warnings
spec:
  type: webhook
  webhook:
    url: "http://localhost:9999/warnings"
    method: POST
    headers:
      Content-Type: application/json
    bodyTemplate: |
      {
        "severity": "{{ .Severity }}",
        "title": "{{ .Title }}",
        "message": "{{ .Message }}",
        "cronjob": "{{ .CronJob.Namespace }}/{{ .CronJob.Name }}"
      }
---
# Webhook channel for info-level notifications
apiVersion: guardian.illenium.net/v1alpha1
kind: AlertChannel
metadata:
  name: slack-info
spec:
  type: webhook
  webhook:
    url: "http://localhost:9999/info"
    method: POST
    headers:
      Content-Type: application/json
    bodyTemplate: |
      {
        "level": "info",
        "title": "{{ .Title }}",
        "cronjob": "{{ .CronJob.Namespace }}/{{ .CronJob.Name }}"
      }
---
# Webhook channel for test alerts
apiVersion: guardian.illenium.net/v1alpha1
kind: AlertChannel
metadata:
  name: slack-test
spec:
  type: webhook
  webhook:
    url: "http://localhost:9999/test"
    method: POST
    headers:
      Content-Type: application/json
    bodyTemplate: |
      {
        "type": "test",
        "alert_type": "{{ .Type }}",
        "severity": "{{ .Severity }}",
        "title": "{{ .Title }}",
        "message": "{{ .Message }}",
        "cronjob": "{{ .CronJob.Namespace }}/{{ .CronJob.Name }}",
        "context": {
          "exit_code": {{ if .Context.ExitCode }}{{ .Context.ExitCode }}{{ else }}0{{ end }},
          "reason": "{{ .Context.Reason }}",
          "suggested_fix": "{{ .Context.SuggestedFix }}"
        }
      }
---
# Webhook channel for analytics
apiVersion: guardian.illenium.net/v1alpha1
kind: AlertChannel
metadata:
  name: slack-analytics
spec:
  type: webhook
  webhook:
    url: "http://localhost:9999/analytics"
    method: POST
    headers:
      Content-Type: application/json
    bodyTemplate: |
      {
        "channel": "analytics",
        "title": "{{ .Title }}",
        "message": "{{ .Message }}"
      }
---
# Webhook channel for performance alerts
apiVersion: guardian.illenium.net/v1alpha1
kind: AlertChannel
metadata:
  name: slack-perf
spec:
  type: webhook
  webhook:
    url: "http://localhost:9999/perf"
    method: POST
    headers:
      Content-Type: application/json
    bodyTemplate: |
      {
        "channel": "performance",
        "severity": "{{ .Severity }}",
        "title": "{{ .Title }}",
        "message": "{{ .Message }}",
        "cronjob": "{{ .CronJob.Namespace }}/{{ .CronJob.Name }}"
      }
